# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{globalize2}
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Sven Fuchs, Joshua Harvey, Clemens Kofler"]
  s.date = %q{2009-12-25}
  s.description = %q{Rails I18n: de-facto standard library for ActiveRecord data translation}
  s.email = %q{joshmh@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.textile"
  ]
  s.files = [
    ".gitignore",
     "LICENSE",
     "README.textile",
     "Rakefile",
     "VERSION",
     "generators/db_backend.rb",
     "generators/templates/db_backend_migration.rb",
     "globalize2.gemspec",
     "init.rb",
     "lib/globalize.rb",
     "lib/globalize/active_record.rb",
     "lib/globalize/active_record/adapter.rb",
     "lib/globalize/active_record/attributes.rb",
     "lib/globalize/active_record/migration.rb",
     "lib/i18n/missing_translations_log_handler.rb",
     "lib/i18n/missing_translations_raise_handler.rb",
     "notes.textile",
     "test/active_record/fallbacks_test.rb",
     "test/active_record/migration_test.rb",
     "test/active_record/sti_translated_test.rb",
     "test/active_record/translates_test.rb",
     "test/active_record/translation_class_test.rb",
     "test/active_record/validation_tests.rb",
     "test/active_record_test.rb",
     "test/all.rb",
     "test/data/models.rb",
     "test/data/no_globalize_schema.rb",
     "test/data/schema.rb",
     "test/i18n/missing_translations_test.rb",
     "test/test_helper.rb"
  ]
  s.homepage = %q{http://github.com/joshmh/globalize2}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Rails I18n: de-facto standard library for ActiveRecord data translation}
  s.test_files = [
    "test/active_record/fallbacks_test.rb",
     "test/active_record/migration_test.rb",
     "test/active_record/sti_translated_test.rb",
     "test/active_record/translates_test.rb",
     "test/active_record/translation_class_test.rb",
     "test/active_record/validation_tests.rb",
     "test/active_record_test.rb",
     "test/all.rb",
     "test/data/models.rb",
     "test/data/no_globalize_schema.rb",
     "test/data/schema.rb",
     "test/i18n/missing_translations_test.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

